### ISSUE TITLE
YouTube video pauses constantly

### ISSUE THREAD

**Issue by ndimatteo** [OriginalEXE/vidim#5] opened 2017-08-22 01:27 UTC
First, I want to say you've done an excellent job with this library. It's easy to setup and I love the fluidity between self-hosted and youtube as options! So, thank you so much for coming up with an elegant solution to this highly popular feature 😎 

One thing I noticed however, is that the video seemingly reloads itself FREQUENTLY. It seems to happen often when I leave the page and come back, resize the browser, or simply wait for it to loop. I'm constantly getting the loading spinner, even though the YouTube video has clearly already loaded fully (testing with a 10 sec clip).

Any ideas why this is? It's unusual and not something I see happening with the more basic CSS implementations of YouTube background videos, which leads me to believe it has to do with how you're looping the video or interacting with the API.

**Comment by OriginalEXE** [comment] 2017-08-22 11:58
Hello,

thanks a lot, glad you found the library useful.

About the issue you are experiencing, does it happen even on the [demo page](https://originalexe.github.io/vidim/)? Which browser are you using when the said issue happens? I just tested my demo page in Chrome and Firefox and could not see the issue you described, I have tried tabbing out and resizing the browser.

**Comment by ndimatteo** [comment] 2017-08-22 14:04
Yes, I noticed it on the demo page a bit as well.

I was testing in Chrome (v60.0.3112.101) on a Mac (OS Sierra 10.12.4)
Here's an example of it on my end of things: https://fresnel-2736654.2010.host/

Definitely getting it regularly on my demo, especially if I tab away and return after 10+ seconds:
![screen shot 2017-08-22 at 10 02 54 am](https://user-images.githubusercontent.com/737188/29569321-26efa1ac-8721-11e7-9e66-90994209061c.png)

**Comment by TwentyOver10** [comment] 2017-08-25 19:29
Any ideas @OriginalEXE ?

**Comment by OriginalEXE** [comment] 2017-08-28 19:30
Hi, apologies for the delay, I am swamped these last few days, lots of things going on.

I have tried to reproduce this on my Mac (10.12.6) in Chrome 60.0.3112.113 and failed to do so. It works without any issues/glitches even when I leave it for some time. I have tried switching tabs and then coming back to it, giving focus to another app and returning to Chrome, etc. but still nothing.

**Comment by OriginalEXE** [comment] 2017-08-28 19:33
What I did notice today was the same kind of spinner you have while watching 4k videos on my MacBook on YouTube, and then switching tabs or opening some other resource-intensive app. So it could be that the spinner shows because Chrome assigns fewer resources to the tabs out of focus? Could you try setting the video quality to something low?

**Comment by OriginalEXE** [comment] 2017-12-04 23:17
Closing this for now, let me know if this happens again.

**Closed as completed by OriginalEXE** 2017-12-04 23:17 UTC
